[package]
name = "dungeon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.2"
dirs = "6.0"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
tempfile = "3.10"
toml = "0.9"
